# Lock screen before suspending and turn on monitor after waking
general {
  #lock_cmd = playerctl --all-players pause ; pidof hyprlock || hyprlock  # avoid starting multiple hyprlock sessions
  lock_cmd = pidof hyprlock || hyprlock  # avoid starting multiple hyprlock sessions
  #on_lock_cmd = playerctl --all-players pause
  before_sleep_cmd = loginctl lock-session                                # lock before suspend
  after_sleep_cmd = hyprctl dipatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display monitor
  ignore_dbus_inhibit = true
}
